export const AIRCRAFTS = Object.freeze([
  Object.freeze({
    id: "al-182",
    name: "AL-182 Skylane",
    shortName: "AL-182",
    category: "Monomoteur",
    description: "École et tourisme · pilotage accessible",
    cruiseSpeed: 124,
    maxSpeed: 165,
    power: "180 hp",
    endurance: "5.2 h",
    ceiling: 14000,
    color: "#d92c38",
    performance: Object.freeze({
      initialSpeed: 105,
      groundSpeed: 88,
      baseAirSpeed: 42,
      throttleAirSpeed: 123,
      pitchDrag: 0.7,
      acceleration: 0.31,
      takeoffSpeed: 52,
      stallSpeed: 55,
      climbPitchFactor: 112,
      climbSpeedReference: 82,
      climbSpeedFactor: 2.1,
      maxClimb: 2200,
      maxDescent: 2600,
      maxRoll: 38,
      rollRate: 52,
      maxPitch: 14,
      pitchRate: 30,
      turnFactor: 0.115,
      safeLandingSpeed: 96,
      autopilotMinSpeed: 75,
      autopilotMaxSpeed: 130,
      fuelBurn: 1,
    }),
  }),
  Object.freeze({
    id: "vt-12",
    name: "VT-12 Velocity",
    shortName: "VT-12",
    category: "Turbopropulseur",
    description: "Voyage rapide · train escamotable",
    cruiseSpeed: 240,
    maxSpeed: 290,
    power: "1 200 shp",
    endurance: "4.4 h",
    ceiling: 30000,
    color: "#f1a62b",
    performance: Object.freeze({
      initialSpeed: 205,
      groundSpeed: 115,
      baseAirSpeed: 70,
      throttleAirSpeed: 220,
      pitchDrag: 1.1,
      acceleration: 0.27,
      takeoffSpeed: 78,
      stallSpeed: 88,
      climbPitchFactor: 160,
      climbSpeedReference: 150,
      climbSpeedFactor: 2.3,
      maxClimb: 3800,
      maxDescent: 3600,
      maxRoll: 44,
      rollRate: 68,
      maxPitch: 16,
      pitchRate: 36,
      turnFactor: 0.105,
      safeLandingSpeed: 125,
      autopilotMinSpeed: 105,
      autopilotMaxSpeed: 260,
      fuelBurn: 1.5,
    }),
  }),
  Object.freeze({
    id: "sj-42",
    name: "SJ-42 Stratus",
    shortName: "SJ-42",
    category: "Jet léger",
    description: "Haute vitesse · double réacteur",
    cruiseSpeed: 420,
    maxSpeed: 480,
    power: "2 × 1 800 lbf",
    endurance: "3.5 h",
    ceiling: 41000,
    color: "#25d6f5",
    performance: Object.freeze({
      initialSpeed: 350,
      groundSpeed: 150,
      baseAirSpeed: 115,
      throttleAirSpeed: 365,
      pitchDrag: 1.6,
      acceleration: 0.22,
      takeoffSpeed: 112,
      stallSpeed: 125,
      climbPitchFactor: 220,
      climbSpeedReference: 260,
      climbSpeedFactor: 2.5,
      maxClimb: 6000,
      maxDescent: 5000,
      maxRoll: 50,
      rollRate: 82,
      maxPitch: 18,
      pitchRate: 44,
      turnFactor: 0.11,
      safeLandingSpeed: 155,
      autopilotMinSpeed: 160,
      autopilotMaxSpeed: 450,
      fuelBurn: 2.2,
    }),
  }),
  Object.freeze({
    id: "fx-19",
    name: "FX-19 Vortex",
    shortName: "FX-19",
    category: "Chasseur supersonique",
    description: "Intercepteur · forte poussée et grande agilité",
    cruiseSpeed: 820,
    maxSpeed: 1450,
    power: "2 × 29 000 lbf",
    endurance: "2.1 h",
    ceiling: 60000,
    color: "#ff7b3d",
    performance: Object.freeze({
      initialSpeed: 650,
      groundSpeed: 260,
      baseAirSpeed: 230,
      throttleAirSpeed: 1220,
      pitchDrag: 2,
      acceleration: 0.32,
      takeoffSpeed: 150,
      stallSpeed: 160,
      climbPitchFactor: 400,
      climbSpeedReference: 450,
      climbSpeedFactor: 3,
      maxClimb: 18000,
      maxDescent: 14000,
      maxRoll: 68,
      rollRate: 125,
      maxPitch: 24,
      pitchRate: 72,
      turnFactor: 0.19,
      safeLandingSpeed: 210,
      autopilotMinSpeed: 260,
      autopilotMaxSpeed: 1350,
      fuelBurn: 4.5,
    }),
  }),
  Object.freeze({
    id: "ufo-x1",
    name: "UFO-X1 Aether",
    shortName: "UFO-X1",
    category: "Soucoupe antigravité",
    description: "Prototype extraterrestre · accélération extrême",
    cruiseSpeed: 2600,
    maxSpeed: 4200,
    power: "Antigravité",
    endurance: "Illimitée",
    enduranceHours: 24,
    ceiling: 120000,
    color: "#a875ff",
    performance: Object.freeze({
      initialSpeed: 1600,
      groundSpeed: 500,
      baseAirSpeed: 400,
      throttleAirSpeed: 3800,
      pitchDrag: 0,
      acceleration: 0.45,
      takeoffSpeed: 20,
      stallSpeed: 0,
      climbPitchFactor: 1200,
      climbSpeedReference: 1500,
      climbSpeedFactor: 0.25,
      maxClimb: 60000,
      maxDescent: 60000,
      maxRoll: 74,
      rollRate: 165,
      maxPitch: 32,
      pitchRate: 105,
      turnFactor: 0.3,
      safeLandingSpeed: 650,
      autopilotMinSpeed: 500,
      autopilotMaxSpeed: 4000,
      fuelBurn: 0.08,
    }),
  }),
]);

export function getAircraft(id) {
  return AIRCRAFTS.find((aircraft) => aircraft.id === id) ?? AIRCRAFTS[0];
}
